### ISSUE TITLE
Question: How to catch user input and redraw

### ISSUE THREAD

**Issue by Sispheor** [pmbarrett314/curses-menu#25]
I want to make something like a filter. The user type a word and I redraw the menu to only show item with the word in it.

But I'm stuck when I run `menu.show()`. 

What should I do to:
- Change the subtitle on the fly after the first "show"
- Catch user input

Thx for any help.

**Comment by SamAlshami** [comment]
This is actually very important, to be able to change the title on the fly. The menu is very simple but the cost is that we are stuck in show()

**Comment by skandabhairava** [comment]
Bump!
Was trying to make a search system too
Also I'm very new to curses!
How do I merge a text box with menu-curses menu screen??

**Comment by pmbarrett314** [comment]
Answering this old one for posterity. You can create a menu without blocking using  menu.start(), implement whatever logic you want to run alongside the menu, and then use menu.join() to make sure the menu exits properly once the user exits it. It behaves like a thread in this regard because it's a thread under the hood.
